language: python
dist: trusty
sudo: false
python:
  - "2.7"
install:
  - pip install -U pip wheel
  - pip install -U setuptools
  - pip install -r requirements.txt
  - apt-get install libgdal-dev
script:
  - make
notifications:
  slack: ccnmtl:GizSNscLWJLldjQrffB8mwgm
